apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: TCP
      port: {{ .Values.service.ports.port }}
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
